---
  - name: Install Windows Updates
    hosts: "{{ match_host }}"
    tasks:
      - name: Just get information about the repository whether or not it has already been cloned locally
        ansible.builtin.git:
          repo: 'https://github.com/lspiehler/win-print-api.git'
          dest: C:/win-print-api
          clone: yes
          update: yes