POST http://127.0.0.1:3000/api/printer/queue/add HTTP/1.1
content-type: application/json

{
    "Name": "Fake printer",
    "Trays": 0,
    "Driver": "Canon MF731C/733C UFR II",
    "Port": "192.168.1.99",
    "Location": "Fake location",
    "Comment": "Fake comment"
}