POST http://127.0.0.1:3000/api/printer/queue/add HTTP/1.1
content-type: application/json

{
    "name": "Fake printer",
    "trays": 0,
    "driver": "Canon MF731C/733C UFR II",
    "port": "192.168.1.99",
    "location": "Fake location",
    "comment": "Fake comment"
}